language: go
sudo: required
go_import_path: cirello.io/pgqueue
go:
  - "1.13.4"

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

install: true

script:
  - docker run -d --name pg12 -e POSTGRES_PASSWORD=mysecretpassword -p 5412:5432 postgres:12
  # - docker run -d --name pg96 -e POSTGRES_PASSWORD=mysecretpassword -p 5496:5432 postgres:9.6
  - PGQUEUE_TEST_DSN=postgres://postgres:mysecretpassword@localhost:5412/postgres?sslmode=disable go test -v . -race
  - PGQUEUE_TEST_DSN=postgres://postgres:mysecretpassword@localhost:5412/postgres?sslmode=disable go test -v . -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  # - PGQUEUE_TEST_DSN=postgres://postgres:mysecretpassword@localhost:5496/postgres?sslmode=disable go test -v .