language: go
sudo: required
go_import_path: cirello.io/pgqueue
go:
  - "1.16"

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

install: true

script:
  - docker run -d --name pg12 -e POSTGRES_PASSWORD=mysecretpassword -p 5413:5432 postgres:13
  - PGQUEUE_TEST_DSN=postgres://postgres:mysecretpassword@localhost:5413/postgres?sslmode=disable go test -mod=mod -v . -race
  - PGQUEUE_TEST_DSN=postgres://postgres:mysecretpassword@localhost:5413/postgres?sslmode=disable go test -mod=mod -v . -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
